// <auto-generated />
using System;
using Looxdex.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Looxdex.Api.Migrations
{
    [DbContext(typeof(LooxdexDbContext))]
    [Migration("20260912191510_AddLookSourceEmbed")]
    partial class AddLookSourceEmbed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Looxdex.Api.Entities.ClosetItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("brand");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("color");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("color_hex");

                    b.Property<DateTime?>("EmbeddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("embedded_at");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("bytea")
                        .HasColumnName("embedding");

                    b.Property<string>("Formality")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("formality");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("boolean")
                        .HasColumnName("is_favorite");

                    b.Property<bool>("IsWishlist")
                        .HasColumnType("boolean")
                        .HasColumnName("is_wishlist");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_key");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("season");

                    b.HasKey("Id")
                        .HasName("pk_closet_items");

                    b.HasIndex("OwnerKey")
                        .HasDatabaseName("ix_closet_items_owner_key");

                    b.ToTable("closet_items", (string)null);
                });

            modelBuilder.Entity("Looxdex.Api.Entities.DetectedItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("BoxHeight")
                        .HasColumnType("double precision")
                        .HasColumnName("box_height");

                    b.Property<double>("BoxWidth")
                        .HasColumnType("double precision")
                        .HasColumnName("box_width");

                    b.Property<double>("BoxX")
                        .HasColumnType("double precision")
                        .HasColumnName("box_x");

                    b.Property<double>("BoxY")
                        .HasColumnType("double precision")
                        .HasColumnName("box_y");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("color_hex");

                    b.Property<string>("ColorName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("color_name");

                    b.Property<string>("CutoutImageId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("cutout_image_id");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("bytea")
                        .HasColumnName("embedding");

                    b.Property<int>("FeedPostId")
                        .HasColumnType("integer")
                        .HasColumnName("feed_post_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<string>("LabelHe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label_he");

                    b.Property<double>("Score")
                        .HasColumnType("double precision")
                        .HasColumnName("score");

                    b.HasKey("Id")
                        .HasName("pk_detected_items");

                    b.HasIndex("FeedPostId")
                        .HasDatabaseName("ix_detected_items_feed_post_id");

                    b.ToTable("detected_items", (string)null);
                });

            modelBuilder.Entity("Looxdex.Api.Entities.EventGroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("event_key");

                    b.Property<string>("EventLabel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("event_label");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("icon");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("SuitcaseId")
                        .HasColumnType("integer")
                        .HasColumnName("suitcase_id");

                    b.HasKey("Id")
                        .HasName("pk_event_groups");

                    b.HasIndex("SuitcaseId")
                        .HasDatabaseName("ix_event_groups_suitcase_id");

                    b.ToTable("event_groups", (string)null);
                });

            modelBuilder.Entity("Looxdex.Api.Entities.FeedPostEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AspectRatioHeight")
                        .HasColumnType("integer")
                        .HasColumnName("aspect_ratio_height");

                    b.Property<int>("AspectRatioWidth")
                        .HasColumnType("integer")
                        .HasColumnName("aspect_ratio_width");

                    b.Property<DateTime?>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<int>("DetectionAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("detection_attempts");

                    b.Property<int>("DetectionState")
                        .HasColumnType("integer")
                        .HasColumnName("detection_state");

                    b.Property<string>("EmbedHtml")
                        .HasColumnType("text")
                        .HasColumnName("embed_html");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("external_id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("image_url");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at");

                    b.Property<int>("Likes")
                        .HasColumnType("integer")
                        .HasColumnName("likes");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("Photographer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("photographer");

                    b.Property<string>("PhotographerUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("photographer_url");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("query");

                    b.Property<long>("Rank")
                        .HasColumnType("bigint")
                        .HasColumnName("rank");

                    b.Property<int>("Source")
                        .HasColumnType("integer")
                        .HasColumnName("source");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("source_url");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_feed_posts");

                    b.HasIndex("DetectionState")
                        .HasDatabaseName("ix_feed_posts_detection_state");

                    b.HasIndex("Rank")
                        .IsDescending()
                        .HasDatabaseName("ix_feed_posts_rank");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_feed_posts_source_external_id");

                    b.ToTable("feed_posts", (string)null);
                });

            modelBuilder.Entity("Looxdex.Api.Entities.OwnerProfileEntity", b =>
                {
                    b.Property<string>("OwnerKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_key");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTime?>("SeededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("seeded_at");

                    b.HasKey("OwnerKey")
                        .HasName("pk_owner_profiles");

                    b.ToTable("owner_profiles", (string)null);
                });

            modelBuilder.Entity("Looxdex.Api.Entities.PackingItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<int?>("ClosetItemId")
                        .HasColumnType("integer")
                        .HasColumnName("closet_item_id");

                    b.Property<int>("EventGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("event_group_id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsPacked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_packed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_packing_items");

                    b.HasIndex("EventGroupId")
                        .HasDatabaseName("ix_packing_items_event_group_id");

                    b.ToTable("packing_items", (string)null);
                });

            modelBuilder.Entity("Looxdex.Api.Entities.SavedPostEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FeedPostId")
                        .HasColumnType("integer")
                        .HasColumnName("feed_post_id");

                    b.Property<string>("Folder")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("folder");

                    b.Property<string>("OwnerKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_key");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("saved_at");

                    b.HasKey("Id")
                        .HasName("pk_saved_posts");

                    b.HasIndex("FeedPostId")
                        .HasDatabaseName("ix_saved_posts_feed_post_id");

                    b.HasIndex("OwnerKey", "FeedPostId")
                        .IsUnique()
                        .HasDatabaseName("ix_saved_posts_owner_key_feed_post_id");

                    b.ToTable("saved_posts", (string)null);
                });

            modelBuilder.Entity("Looxdex.Api.Entities.ShoppingAlternativeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("brand");

                    b.Property<int>("DetectedItemId")
                        .HasColumnType("integer")
                        .HasColumnName("detected_item_id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("StoreUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("store_url");

                    b.HasKey("Id")
                        .HasName("pk_shopping_alternatives");

                    b.HasIndex("DetectedItemId")
                        .HasDatabaseName("ix_shopping_alternatives_detected_item_id");

                    b.ToTable("shopping_alternatives", (string)null);
                });

            modelBuilder.Entity("Looxdex.Api.Entities.SuitcaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("cover_image_url");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("destination");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<double>("ExpectedTempHigh")
                        .HasColumnType("double precision")
                        .HasColumnName("expected_temp_high");

                    b.Property<double>("ExpectedTempLow")
                        .HasColumnType("double precision")
                        .HasColumnName("expected_temp_low");

                    b.Property<string>("OwnerKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_key");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("TripName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("trip_name");

                    b.HasKey("Id")
                        .HasName("pk_suitcases");

                    b.HasIndex("OwnerKey")
                        .HasDatabaseName("ix_suitcases_owner_key");

                    b.ToTable("suitcases", (string)null);
                });

            modelBuilder.Entity("Looxdex.Api.Entities.UploadedImageEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("id");

                    b.Property<int>("ByteSize")
                        .HasColumnType("integer")
                        .HasColumnName("byte_size");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("data");

                    b.Property<string>("OwnerKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_key");

                    b.HasKey("Id")
                        .HasName("pk_uploaded_images");

                    b.HasIndex("OwnerKey")
                        .HasDatabaseName("ix_uploaded_images_owner_key");

                    b.ToTable("uploaded_images", (string)null);
                });

            modelBuilder.Entity("Looxdex.Api.Entities.DetectedItemEntity", b =>
                {
                    b.HasOne("Looxdex.Api.Entities.FeedPostEntity", "FeedPost")
                        .WithMany("DetectedItems")
                        .HasForeignKey("FeedPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_detected_items_feed_posts_feed_post_id");

                    b.Navigation("FeedPost");
                });

            modelBuilder.Entity("Looxdex.Api.Entities.EventGroupEntity", b =>
                {
                    b.HasOne("Looxdex.Api.Entities.SuitcaseEntity", "Suitcase")
                        .WithMany("EventGroups")
                        .HasForeignKey("SuitcaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_groups_suitcases_suitcase_id");

                    b.Navigation("Suitcase");
                });

            modelBuilder.Entity("Looxdex.Api.Entities.PackingItemEntity", b =>
                {
                    b.HasOne("Looxdex.Api.Entities.EventGroupEntity", "EventGroup")
                        .WithMany("Items")
                        .HasForeignKey("EventGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_packing_items_event_groups_event_group_id");

                    b.Navigation("EventGroup");
                });

            modelBuilder.Entity("Looxdex.Api.Entities.SavedPostEntity", b =>
                {
                    b.HasOne("Looxdex.Api.Entities.FeedPostEntity", "FeedPost")
                        .WithMany()
                        .HasForeignKey("FeedPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_saved_posts_feed_posts_feed_post_id");

                    b.Navigation("FeedPost");
                });

            modelBuilder.Entity("Looxdex.Api.Entities.ShoppingAlternativeEntity", b =>
                {
                    b.HasOne("Looxdex.Api.Entities.DetectedItemEntity", "DetectedItem")
                        .WithMany("Alternatives")
                        .HasForeignKey("DetectedItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shopping_alternatives_detected_items_detected_item_id");

                    b.Navigation("DetectedItem");
                });

            modelBuilder.Entity("Looxdex.Api.Entities.DetectedItemEntity", b =>
                {
                    b.Navigation("Alternatives");
                });

            modelBuilder.Entity("Looxdex.Api.Entities.EventGroupEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Looxdex.Api.Entities.FeedPostEntity", b =>
                {
                    b.Navigation("DetectedItems");
                });

            modelBuilder.Entity("Looxdex.Api.Entities.SuitcaseEntity", b =>
                {
                    b.Navigation("EventGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
