// <auto-generated />
using System;
using Looxdex.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Looxdex.Api.Migrations
{
    [DbContext(typeof(LooxdexDbContext))]
    partial class LooxdexDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("Looxdex.Api.Entities.ClosetItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmbeddedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("BLOB");

                    b.Property<string>("Formality")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerKey");

                    b.ToTable("ClosetItems");
                });

            modelBuilder.Entity("Looxdex.Api.Entities.DetectedItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BoxHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("BoxWidth")
                        .HasColumnType("REAL");

                    b.Property<double>("BoxX")
                        .HasColumnType("REAL");

                    b.Property<double>("BoxY")
                        .HasColumnType("REAL");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Embedding")
                        .HasColumnType("BLOB");

                    b.Property<int>("FeedPostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelHe")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("Score")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("FeedPostId");

                    b.ToTable("DetectedItems");
                });

            modelBuilder.Entity("Looxdex.Api.Entities.EventGroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventLabel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuitcaseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SuitcaseId");

                    b.ToTable("EventGroups");
                });

            modelBuilder.Entity("Looxdex.Api.Entities.FeedPostEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AspectRatioHeight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AspectRatioWidth")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DetectionAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DetectionState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Likes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Photographer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotographerUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetectionState");

                    b.HasIndex("Rank")
                        .IsDescending();

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique();

                    b.ToTable("FeedPosts");
                });

            modelBuilder.Entity("Looxdex.Api.Entities.PackingItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClosetItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EventGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPacked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EventGroupId");

                    b.ToTable("PackingItems");
                });

            modelBuilder.Entity("Looxdex.Api.Entities.SavedPostEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FeedPostId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OwnerKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FeedPostId");

                    b.HasIndex("OwnerKey", "FeedPostId")
                        .IsUnique();

                    b.ToTable("SavedPosts");
                });

            modelBuilder.Entity("Looxdex.Api.Entities.ShoppingAlternativeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("DetectedItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DetectedItemId");

                    b.ToTable("ShoppingAlternatives");
                });

            modelBuilder.Entity("Looxdex.Api.Entities.SuitcaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("ExpectedTempHigh")
                        .HasColumnType("REAL");

                    b.Property<double>("ExpectedTempLow")
                        .HasColumnType("REAL");

                    b.Property<string>("OwnerKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TripName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerKey");

                    b.ToTable("Suitcases");
                });

            modelBuilder.Entity("Looxdex.Api.Entities.DetectedItemEntity", b =>
                {
                    b.HasOne("Looxdex.Api.Entities.FeedPostEntity", "FeedPost")
                        .WithMany("DetectedItems")
                        .HasForeignKey("FeedPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeedPost");
                });

            modelBuilder.Entity("Looxdex.Api.Entities.EventGroupEntity", b =>
                {
                    b.HasOne("Looxdex.Api.Entities.SuitcaseEntity", "Suitcase")
                        .WithMany("EventGroups")
                        .HasForeignKey("SuitcaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Suitcase");
                });

            modelBuilder.Entity("Looxdex.Api.Entities.PackingItemEntity", b =>
                {
                    b.HasOne("Looxdex.Api.Entities.EventGroupEntity", "EventGroup")
                        .WithMany("Items")
                        .HasForeignKey("EventGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventGroup");
                });

            modelBuilder.Entity("Looxdex.Api.Entities.SavedPostEntity", b =>
                {
                    b.HasOne("Looxdex.Api.Entities.FeedPostEntity", "FeedPost")
                        .WithMany()
                        .HasForeignKey("FeedPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeedPost");
                });

            modelBuilder.Entity("Looxdex.Api.Entities.ShoppingAlternativeEntity", b =>
                {
                    b.HasOne("Looxdex.Api.Entities.DetectedItemEntity", "DetectedItem")
                        .WithMany("Alternatives")
                        .HasForeignKey("DetectedItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetectedItem");
                });

            modelBuilder.Entity("Looxdex.Api.Entities.DetectedItemEntity", b =>
                {
                    b.Navigation("Alternatives");
                });

            modelBuilder.Entity("Looxdex.Api.Entities.EventGroupEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Looxdex.Api.Entities.FeedPostEntity", b =>
                {
                    b.Navigation("DetectedItems");
                });

            modelBuilder.Entity("Looxdex.Api.Entities.SuitcaseEntity", b =>
                {
                    b.Navigation("EventGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
